Repository googleapis/nodejs-web-security-scanner, pull requests merged in 2021-02, with the labels that each got.

#8 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes

#7 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#10 build: correct package name for npm
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/gapic_metadata.json
  src/v1/index.ts
  src/v1/web_security_scanner_client.ts
  src/v1alpha/gapic_metadata.json
  src/v1alpha/index.ts
  src/v1alpha/web_security_scanner_client.ts
  src/v1beta/gapic_metadata.json
  src/v1beta/index.ts
  src/v1beta/web_security_scanner_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_web_security_scanner_v1.ts
  test/gapic_web_security_scanner_v1alpha.ts
  test/gapic_web_security_scanner_v1beta.ts
Labels: cla: yes, context: partial

#11 chore: update flakybot config and sample index
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: cla: yes, context: full
